/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../utils/chordUtils`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson1` | `/lesson1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson2` | `/lesson2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson3` | `/lesson3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson4` | `/lesson4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson5` | `/lesson5`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/licao` | `/licao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/loja` | `/loja`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/musica` | `/musica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test-lessons` | `/test-lessons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trilha` | `/trilha`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Lessons/LessonScreen`; params?: Router.UnknownInputParams; } | { pathname: `/lesson/[lessonId]`, params: Router.UnknownInputParams & { lessonId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../utils/chordUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lesson1` | `/lesson1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lesson2` | `/lesson2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lesson3` | `/lesson3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lesson4` | `/lesson4`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lesson5` | `/lesson5`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/licao` | `/licao`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/loja` | `/loja`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/musica` | `/musica`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/test-lessons` | `/test-lessons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trilha` | `/trilha`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Lessons/LessonScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/lesson/[lessonId]`, params: Router.UnknownOutputParams & { lessonId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../utils/chordUtils${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lesson1${`?${string}` | `#${string}` | ''}` | `/lesson1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lesson2${`?${string}` | `#${string}` | ''}` | `/lesson2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lesson3${`?${string}` | `#${string}` | ''}` | `/lesson3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lesson4${`?${string}` | `#${string}` | ''}` | `/lesson4${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lesson5${`?${string}` | `#${string}` | ''}` | `/lesson5${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/licao${`?${string}` | `#${string}` | ''}` | `/licao${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/loja${`?${string}` | `#${string}` | ''}` | `/loja${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/musica${`?${string}` | `#${string}` | ''}` | `/musica${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/test-lessons${`?${string}` | `#${string}` | ''}` | `/test-lessons${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trilha${`?${string}` | `#${string}` | ''}` | `/trilha${`?${string}` | `#${string}` | ''}` | `/screens/Lessons/LessonScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../utils/chordUtils`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson1` | `/lesson1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson2` | `/lesson2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson3` | `/lesson3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson4` | `/lesson4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lesson5` | `/lesson5`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/licao` | `/licao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/loja` | `/loja`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/musica` | `/musica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test-lessons` | `/test-lessons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trilha` | `/trilha`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Lessons/LessonScreen`; params?: Router.UnknownInputParams; } | `/lesson/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/lesson/[lessonId]`, params: Router.UnknownInputParams & { lessonId: string | number; } };
    }
  }
}
